"""Reproduce the original Lecture 7 comparison of DDPM noise schedules.

Nichol & Dhariwal (2021), Sec. 3.2: https://arxiv.org/abs/2102.09672
Run with Python, NumPy and Matplotlib; writes the local SVG and its provenance.
"""

from pathlib import Path
import hashlib
import json

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from matplotlib.font_manager import FontProperties
import numpy as np


lecture = Path(__file__).resolve().parents[1]
steps = 1000
t = np.arange(1, steps + 1)
beta_linear = np.linspace(0.0001, 0.02, steps)
alpha_linear = np.cumprod(1 - beta_linear)
offset = 0.008
f = np.cos((np.arange(steps + 1) / steps + offset) / (1 + offset) * np.pi / 2) ** 2
beta_cosine = np.minimum(1 - f[1:] / f[:-1], 0.999)
alpha_cosine = np.cumprod(1 - beta_cosine)

def log_snr(alpha_bar):
    return np.log(alpha_bar) - np.log1p(-alpha_bar)


plt.rcParams.update({
    "font.family": "Arial",
    "font.size": 20,
    "text.color": "#17324d",
    "axes.labelcolor": "#17324d",
    "xtick.color": "#587083",
    "ytick.color": "#587083",
    "axes.edgecolor": "#9aadb9",
    "axes.spines.top": False,
    "axes.spines.right": False,
    "svg.fonttype": "path",
    "svg.hashsalt": "lecture7-noise-schedules",
})
fig, ax = plt.subplots(figsize=(7.52, 4.34), dpi=100)
fig.subplots_adjust(left=0.14, right=0.975, top=0.965, bottom=0.20)
ax.plot(t / steps, log_snr(alpha_linear), color="#17324d", lw=2.4, label="Linear beta")
ax.plot(t / steps, log_snr(alpha_cosine), color="#007f82", lw=2.4, label="Cosine")
ax.set(xlim=(0, 1), ylim=(-12, 10), xlabel="Diffusion time  t / T", ylabel="log-SNR")
ax.set_xticks([0, 0.25, 0.5, 0.75, 1], ["0", "0.25", "0.5", "0.75", "1"])
ax.set_yticks([-10, -5, 0, 5, 10])
ax.grid(color="#e2e9ee", linewidth=0.7)
ax.axhline(0, color="#9aadb9", lw=0.8)
ax.set_axisbelow(True)
ax.legend(loc="upper right", frameon=False, prop=FontProperties(family="Arial", size=20))
asset = lecture / "public/figs/noise-schedules.svg"
fig.savefig(asset, format="svg", metadata={"Date": None, "Title": "DDPM noise schedules through log-SNR"})
plt.close(fig)

provenance = asset.parent / "sources.json"
sources = json.loads(provenance.read_text()) if provenance.exists() else {}
sources[asset.name] = {
    "source": "https://arxiv.org/abs/2102.09672",
    "description": "Original plot generated by scripts/generate-noise-schedules.py from the paper's noise schedules, not copied from a paper figure. T=1000; linear beta from 0.0001 to 0.02; cosine alpha-bar with s=0.008 and beta clipped at 0.999. Natural log-SNR is shown for t=1,...,T; vertical range [-12,10] crops the extreme endpoints.",
    "sha256": hashlib.sha256(asset.read_bytes()).hexdigest(),
    "asset_kind": "original numerical plot",
}
provenance.write_text(json.dumps(sources, indent=2) + "\n")
print(asset)
